Fixed 13.6 -> 14 TeV rounding error
JHUGen/JHUGenMELA pull request #26
Opened 2023-07-14 15:54 UTC by michael11892

2023-07-14 15:56 UTC, usarica requested changes
At the moment, the calibration files for 13.6 (or 14) TeV do not exist in data/, so this PR would only make sense to merge once those calibration files are available. That depends on CMS production status, which has not even started yet.

2023-07-14 16:17 UTC, gritsan submitted a review, later dismissed
This change is really needed, thanks for making it!

2023-07-14 16:19 UTC, gritsan commented
> At the moment, the calibration files for 13.6 (or 14) TeV do not exist in data/, 
> so this PR would only make sense to merge once those calibration files are available. 
> That depends on CMS production status, which has not even started yet.

There are two issues: lack of 13.6 calibration and wrong treatment of energy. This PR fixes the code issue of integer energy expectation. We must approve this request, as it is needed for Run-3 studies urgently. The calibration files from 13.0 TeV could be used in the meantime.

2023-07-14 16:20 UTC, gritsan commented
This is a HOTFIX!!!

2023-07-14 16:24 UTC, usarica commented
> This PR fixes the code issue

No it doesn't as long as it refers to a file that includes 13.6TeV in the name, which does not exist yet. The proper interim fix would floor the float.

2023-07-14 16:25 UTC, gritsan commented
This is not a transparent solution, which confused every single person who looked at this.

2023-07-14 17:01 UTC, usarica commented
> This is not a transparent solution, which confused every single person who looked at this.

One could also consider scanning for the available sqrts values and then picking the closest one if the needed file is unavailable.. However, as the PR currently stands, it does not address the problem by opening the 13TeV files when sqrts=13.6 TeV. For that reason, the PR should be revised, whether the implemented solution is confusing or not.

2023-07-14 18:39 UTC, hroskes submitted a review, later dismissed

2023-07-14 21:17 UTC, usarica requested changes
If you would like to pursue a non-searchable option, I think this optional argument is not needed. All you would need to do is something like.
int isqrts = sqrts;
...
Form("...%iTeV...", isqrts...)

Since this is an interim fix due to the way it is currently progressing, all tags need to be marked as 'pre-release' until a searchable solution is implemented, or we edit these lines again to accommodate 13p6TeV files that will be generated in the future, albeit at an undetermined time scale.

2023-07-14 21:24 UTC, michael11892 commented
I see no merit in removing the proposed fix for the sake of a floor command which will be, by definition, overhauled at a later date. The additional option allows for the floor "interim fix" until production is ready.

2023-07-14 21:34 UTC, usarica commented
> I see no merit in removing the proposed fix for the sake of a floor command which will be, by definition, overhauled at a later date. The additional option allows for the floor "interim fix" until production is ready.

There is always a danger in putting code that is more complex than necessary. While you might not see a merit, the complexity of the code in this case has resulted in a bug already, which also tells me the commits are done without checking whether they work: L39 is set to false, and for the purpose of the interim fix for which it is implemented, it should have been set to true. That is why keeping the code as simple as possible helps.

Given that there are two solutions, one interim and one more permanent, I would suggest to split these into two separate PRs, with the permanent solution PR already starting from the interim solution PR so that both PRs can be merged in due time, and we won't have to remember or revisit these solutions in depth - and the fact that a PR is pending would act as a permanent reminder of its relevance when the CMS files are ready.

Once you split the PR, I would be happy to merge the interim version. Thanks.

2023-07-14 21:37 UTC, michael11892 commented
The default value was intentionally set to false, that is no bug. However, your last proposed solution works nicely in this case. I will proceed to make one PR with the interim solution properly implemented and another for the interm fix's replacement, which can be merged in due time.

2023-07-14 21:52 UTC, usarica approved these changes

2023-07-15 02:59 UTC, gritsan approved these changes

2023-07-15 02:59 UTC, merged