Adding RenFacScheme Getter
JHUGen/JHUGenMELA pull request #44
Opened 2024-02-13 12:03 UTC by MohitS704

There is currently no way to access the current factorization scheme that MELA uses at any given point. This fixes that.

I've mimicked the pipeline of set_RenFacScheme to have get_RenFacScheme (it goes through ZZMatrixElement then through TUtil), where it returns the TVar::event_scales_type that someone can then access on their own.

2024-02-13 14:45 UTC, gritsan submitted a review, later dismissed

2024-02-13 15:50 UTC, usarica requested changes

2024-02-13 15:50 UTC, usarica commented on MELA/src/Mela.cc
> +TVar::event_scales_type Mela::get_RenFacScaleMode(){
get_ -> get

2024-02-13 15:50 UTC, usarica commented on MELA/src/TEvtProb.cc
> +  }
I would either remove these or remake the reference files in case any of them call SetRenFacScaleMode.

2024-02-15 07:20 UTC, usarica requested changes
One more request: get functions should have the const keyword associated. If possible, they should also return const-reference (I leave it to you to find out why).

2024-02-29 17:19 UTC, MohitS704 commented
> One more request: get functions should have the const keyword associated. If possible, they should also return const-reference (I leave it to you to find out why).

This has been done.

2024-02-29 23:29 UTC, usarica requested changes

2024-02-29 23:29 UTC, usarica commented on MELA/interface/Mela.h
> +  const TVar::event_scales_type& getRenFacScaleMode();
Should be

`const TVar::event_scales_type& getRenFacScaleMode() **const**;`

(Similar everywhere else)

2024-02-29 23:31 UTC, usarica commented
> > One more request: get functions should have the const keyword associated. If possible, they should also return const-reference (I leave it to you to find out why).
> 
> This has been done.

What I meant was the function qualifier, not just the qualifier of its return type.

2024-03-04 15:39 UTC, usarica approved these changes

2024-03-04 15:40 UTC, gritsan approved these changes

2024-03-04 15:40 UTC, merged

2024-03-04 15:41 UTC, usarica requested changes
Function signatures also need to match in source files.

2024-03-04 15:50 UTC, usarica commented
Please reopen a new PR reverting #46 and implementing the above comment.

In general, please do not push and/or flag as done before you are sure MELA actually compiles.